substitutions:
  name: boneio-c-07
  friendly_name: 'BoneIO ESP Cover'
  serial_prefix: 'esp' #Don't change it.

esphome:
  name: '${name}'
  friendly_name: '${friendly_name}'
  name_add_mac_suffix: true  
  project:
    name: boneio.32x10-cover
    version: '0.7'
    
  on_boot:
    priority: 800
    then:
      - lambda: |-
          button_01.set_cover(id(cover_01));
          button_02.set_cover(id(cover_02));
          button_03.set_cover(id(cover_03));
          button_04.set_cover(id(cover_04));
          button_05.set_cover(id(cover_05));
          button_06.set_cover(id(cover_06));
          button_07.set_cover(id(cover_07));
          button_08.set_cover(id(cover_08));
          button_09.set_cover(id(cover_09));
          button_10.set_cover(id(cover_10));
          button_11.set_cover(id(cover_11));
          button_12.set_cover(id(cover_12));
          button_13.set_cover(id(cover_13));
          button_14.set_cover(id(cover_14));

          

esp32:
  board: nodemcu-32s
  framework:                                                                            
    type: esp-idf

external_components:
  - source:
      type: git
      url: https://github.com/thomaswinklehner/VenetianBlindsOneButton
      ref: master
    components: [cover_button]

ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO0
    mode: CLK_EXT_IN
  phy_addr: 1
  power_pin: GPIO16
  use_address: 192.168.0.127

dashboard_import:
  package_import_url: github://boneIO-eu/esphome/boneio-cover_v0_7.yaml@latest
  import_full_config: true

packages:
  internals_packages:
    url: https://github.com/boneIO-eu/esphome
    ref: v1.7.1
    files: [
        'devices/buzzer.yaml',
        'devices/serial_no.yaml',
        'devices_v0_7/display.yaml',
        'devices_v0_7/i2c.yaml',
        'devices_v0_7-v0_9/ina219.yaml',
        'devices_v0_7-v0_9/lm75b.yaml',
        'devices_v0_7-v0_9/pcf.yaml',
        'boards/cover/out01_02.yaml',
        'boards/cover/out03_04.yaml',
        'boards/cover/out05_06.yaml',
        'boards/cover/out07_08.yaml',
        'boards/cover/out09_10.yaml',
        'boards/cover/out11_12.yaml',
        'boards/cover/out13_14.yaml',
        'boards/cover/out15_16.yaml',
        'boards/cover/out17_18.yaml',
        'boards/cover/out19_20.yaml',
        'boards/cover/out21_22.yaml',
        'boards/cover/out23_24.yaml',
        'boards/cover/out25_26.yaml',
        'boards/cover/out27_28.yaml',
        'boards/cover/out29_30.yaml',
        'boards/cover/out31_32.yaml',
        # 'devices_v0_7-v0_9/one_wire.yaml',
      ]

logger:
api:
  reboot_timeout: 0s
ota:
  - platform: esphome
  - platform: web_server

web_server:
  port: 80
  local: true

time:
  - platform: homeassistant
    timezone: Europe/Warsaw
    id: homeassistant_time

cover:
  # =========================
  # VENETIAN BLINDS 01-06
  # =========================

  - platform: venetian_blinds
    name: 'K che'
    id: cover_01
    open_action:
      - switch.turn_on: cover_open_01_out01
    open_duration: 60s
    close_action:    
      - if:
          condition:
            binary_sensor.is_off: wind_alarm
          then:
            - switch.turn_on: cover_close_01_out02
    close_duration: 60s
    tilt_duration: 2000ms
    stop_action:
      - switch.turn_off: cover_open_01_out01
      - switch.turn_off: cover_close_01_out02

  - platform: venetian_blinds
    name: 'EZ S D'
    id: cover_02
    open_action:
      - switch.turn_on: cover_open_02_out03
    open_duration: 60s
    close_action:
      - if:
          condition:
            binary_sensor.is_off: wind_alarm
          then:
            - switch.turn_on: cover_close_02_out04
    close_duration: 60s
    tilt_duration: 2000ms
    stop_action:
      - switch.turn_off: cover_open_02_out03
      - switch.turn_off: cover_close_02_out04

  - platform: venetian_blinds
    name: 'EZ HEBE S D'
    id: cover_03
    open_action:
      - switch.turn_on: cover_open_03_out05
    open_duration: 60s
    close_action:
      - if:
          condition:
            binary_sensor.is_off: wind_alarm
          then:
            - switch.turn_on: cover_close_03_out06
    close_duration: 60s
    tilt_duration: 2000ms
    stop_action:
      - switch.turn_off: cover_open_03_out05
      - switch.turn_off: cover_close_03_out06

  - platform: venetian_blinds
    name: 'EZ HEBE NORD'
    id: cover_04
    open_action:
      - switch.turn_on: cover_open_04_out07
    open_duration: 60s
    close_action:
      - if:
          condition:
            binary_sensor.is_off: wind_alarm
          then:
            - switch.turn_on: cover_close_04_out08
    close_duration: 60s
    tilt_duration: 2000ms
    stop_action:
      - switch.turn_off: cover_open_04_out07
      - switch.turn_off: cover_close_04_out08

  - platform: venetian_blinds
    name: 'WZ'
    id: cover_05
    open_action:
      - switch.turn_on: cover_open_05_out09
    open_duration: 60s
    close_action:
      - if:
          condition:
            binary_sensor.is_off: wind_alarm
          then:
            - switch.turn_on: cover_close_05_out10
    close_duration: 60s
    tilt_duration: 2000ms
    stop_action:
      - switch.turn_off: cover_open_05_out09
      - switch.turn_off: cover_close_05_out10


  # =========================
  # ROLLER SHUTTERS 06-13
  # =========================

  - platform: venetian_blinds
    name: 'G ste West'
    id: cover_06
    open_action:
      - switch.turn_on: cover_open_06_out11
    open_duration: 60s
    close_action:
      - if:
          condition:
            binary_sensor.is_off: wind_alarm
          then:
            - switch.turn_on: cover_close_06_out12
    close_duration: 60s
    tilt_duration: 2000ms
    stop_action:
      - switch.turn_off: cover_open_06_out11
      - switch.turn_off: cover_close_06_out12



  - platform: venetian_blinds
    name: 'G ste Nord'
    id: cover_07
    open_action:
      - switch.turn_on: cover_open_07_out13
    open_duration: 60s
    close_action:
      - if:
          condition:
            binary_sensor.is_off: wind_alarm
          then:
             - switch.turn_on: cover_close_07_out14
    close_duration: 60s
    tilt_duration: 2000ms
    stop_action:
      - switch.turn_off: cover_open_07_out13
      - switch.turn_off: cover_close_07_out14

  - platform: venetian_blinds
    name: 'KZ OST OST'
    id: cover_08
    open_action:
      - switch.turn_on: cover_open_08_out15
    open_duration: 60s
    close_action:
      - if:
          condition:
            binary_sensor.is_off: wind_alarm
          then:
            - switch.turn_on: cover_close_08_out16
    close_duration: 60s
    tilt_duration: 2000ms
    stop_action:
      - switch.turn_off: cover_open_08_out15
      - switch.turn_off: cover_close_08_out16

  - platform: venetian_blinds
    name: 'KZ OST S D'
    id: cover_09
    open_action:
      - switch.turn_on: cover_open_09_out17
    open_duration: 60s
    close_action:
      - if:
          condition:
            binary_sensor.is_off: wind_alarm
          then:
            - switch.turn_on: cover_close_09_out18
    close_duration: 60s
    tilt_duration: 2000ms
    stop_action:
      - switch.turn_off: cover_open_09_out17
      - switch.turn_off: cover_close_09_out18

  - platform: venetian_blinds
    name: 'KZ WEST S D'
    id: cover_10
    open_action:
      - switch.turn_on: cover_open_10_out19
    open_duration: 60s
    close_action:
      - if:
          condition:
            binary_sensor.is_off: wind_alarm
          then:
             - switch.turn_on: cover_close_10_out20
    close_duration: 60s
    tilt_duration: 2000ms
    stop_action:
      - switch.turn_off: cover_open_10_out19
      - switch.turn_off: cover_close_10_out20

  - platform: venetian_blinds
    name: 'KZ WEST WEST'
    id: cover_11
    open_action:
      - switch.turn_on: cover_open_11_out21
    open_duration: 60s
    close_action:
      - if:
          condition:
            binary_sensor.is_off: wind_alarm
          then:
             - switch.turn_on: cover_close_11_out22
    close_duration: 60s
    tilt_duration: 2000ms
    stop_action:
      - switch.turn_off: cover_open_11_out21
      - switch.turn_off: cover_close_11_out22

  - platform: venetian_blinds
    name: 'SR'
    id: cover_12
    open_action:
      - switch.turn_on: cover_open_12_out23
    open_duration: 60s
    close_action:
      - if:
          condition:
            binary_sensor.is_off: wind_alarm
          then:
            - switch.turn_on: cover_close_12_out24
    close_duration: 60s
    tilt_duration: 2000ms
    stop_action:
      - switch.turn_off: cover_open_12_out23
      - switch.turn_off: cover_close_12_out24

  - platform: venetian_blinds
    name: 'SZ'
    id: cover_13
    open_action:
      - switch.turn_on: cover_open_13_out25
    open_duration: 60s
    close_action:
      - if:
          condition:
            binary_sensor.is_off: wind_alarm
          then:
            - switch.turn_on: cover_close_13_out26
    close_duration: 60s
    tilt_duration: 2000ms
    stop_action:
      - switch.turn_off: cover_open_13_out25
      - switch.turn_off: cover_close_13_out26

  # =========================
  # VENETIAN BLIND 14
  # =========================

  - platform: venetian_blinds
    name: 'ReserveRaff'
    id: cover_14
    open_action:
      - switch.turn_on: cover_open_14_out27
    open_duration: 60s
    close_action:
      - if:
          condition:
            binary_sensor.is_off: wind_alarm
          then:
            - switch.turn_on: cover_close_14_out28
    close_duration: 60s
    tilt_duration: 2000ms
    stop_action:
      - switch.turn_off: cover_open_14_out27
      - switch.turn_off: cover_close_14_out28







binary_sensor:

  - platform: gpio
    name: '01_Küche'
    id: in_01

    pin:
      pcf8574: pcf_inputs_1to14
      number: 0
      mode:
        input: true
      inverted: true

    on_multi_click:

      - timing:
          - ON for at least 2s
          - ON for at most 5s
          - OFF for at least 0.1s
        then:
          - lambda: |-
              button_01.all_press();

      - timing:
          - ON for at least 1s
          - ON for at most 1.99s
          - OFF for at least 0.1s
        then:
          - lambda: |-
              button_01.stop_press();

      - timing:
          - ON for at most 0.99s
          - OFF for at least 0.1s
        then:
          - lambda: |-
              button_01.short_press();

  # --- Cover 02 ---
  - platform: gpio
    name: '03_EZ_S D_Auf'
    id: in_03
    pin:
      pcf8574: pcf_inputs_1to14
      number: 2
      mode:
        input: true
      inverted: true
    on_multi_click:

      - timing:
          - ON for at least 2s
          - ON for at most 5s
          - OFF for at least 0.1s
        then:
          - lambda: |-
              button_02.all_press();

      - timing:
          - ON for at least 1s
          - ON for at most 1.99s
          - OFF for at least 0.1s
        then:
          - lambda: |-
              button_02.stop_press();

      - timing:
          - ON for at most 0.99s
          - OFF for at least 0.1s
        then:
          - lambda: |-
              button_02.short_press();


  - platform: gpio
    name: "29_Wind Alarm"
    id: wind_alarm
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 0
      mode:
        input: true
      inverted: true   # NC contact -> OFF = alarm

    filters:
      - delayed_on: 2s   # ignore short glitches

    on_press:
      then:
        - logger.log: "WIND ALARM - Opening all covers"
        - cover.open: cover_01
        - cover.open: cover_02
        - cover.open: cover_03
        - cover.open: cover_04
        - cover.open: cover_05
        - cover.open: cover_06
        - cover.open: cover_07
        - cover.open: cover_08
        - cover.open: cover_09
        - cover.open: cover_10
        - cover.open: cover_11
        - cover.open: cover_12
        - cover.open: cover_13
        - cover.open: cover_14



######################
### MODBUS SECTION ###
######################
# UNCOMMENT BELOW TO USE MODBUS
# uart:
#   id: uart_pin14_15
#   rx_pin: GPIO14
#   tx_pin: GPIO15
#   baud_rate: 9600
#   stop_bits: 1

# modbus:
#   send_wait_time: 200ms
#   uart_id: uart_pin14_15
#   id: boneio_modbus