substitutions:
  name: boneio-c-07
  friendly_name: 'BoneIO ESP Cover'
  serial_prefix: 'esp'
  external_component_ref: develop

esphome:
  name: '${name}'
  friendly_name: '${friendly_name}'
  name_add_mac_suffix: true
  project:
    name: thomaswinklehner.venetian-blinds-one-button
    version: '1.0.0'
  on_boot:
    - priority: 1001
      then:
        - lambda: |-
            gpio_reset_pin((gpio_num_t) 14);
            gpio_reset_pin((gpio_num_t) 15);

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

external_components:
  - source:
      type: git
      url: https://github.com/thomaswinklehner/VenetianBlindsOneButton
      ref: '${external_component_ref}'
    components:
      - cover_button
      - venetian_blinds

ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO0
    mode: CLK_EXT_IN
  phy_addr: 1
  power_pin: GPIO16

dashboard_import:
  package_import_url: github://thomaswinklehner/VenetianBlindsOneButton/RolloConfig.yaml@develop
  import_full_config: true

packages:
  internals_packages:
    url: https://github.com/boneIO-eu/esphome
    ref: packages-v2.1.0
    files:
      - 'packages/devices/buzzer.yaml'
      - 'packages/devices/serial_no.yaml'
      - 'packages/devices_v0_7/display.yaml'
      - 'packages/devices_v0_7/i2c.yaml'
      - 'packages/devices_v0_7-v0_9/ina219.yaml'
      - 'packages/devices_v0_7-v0_9/lm75b.yaml'
      - 'packages/devices_v0_7-v0_9/pcf.yaml'
      - 'packages/boards/cover/out01_02.yaml'
      - 'packages/boards/cover/out03_04.yaml'
      - 'packages/boards/cover/out05_06.yaml'
      - 'packages/boards/cover/out07_08.yaml'
      - 'packages/boards/cover/out09_10.yaml'
      - 'packages/boards/cover/out11_12.yaml'
      - 'packages/boards/cover/out13_14.yaml'
      - 'packages/boards/cover/out15_16.yaml'
      - 'packages/boards/cover/out17_18.yaml'
      - 'packages/boards/cover/out19_20.yaml'
      - 'packages/boards/cover/out21_22.yaml'
      - 'packages/boards/cover/out23_24.yaml'
      - 'packages/boards/cover/out25_26.yaml'
      - 'packages/boards/cover/out27_28.yaml'

logger:

api:
  reboot_timeout: 0s

ota:
  - platform: esphome
  - platform: web_server

web_server:
  port: 80
  local: true

time:
  - platform: homeassistant
    timezone: Europe/Warsaw
    id: homeassistant_time

cover:
  - platform: venetian_blinds
    name: 'Küche'
    id: cover_01
    device_class: blind
    open_action:
      - switch.turn_on: cover_open_01_out01
    open_duration: 60s
    close_action:
      - switch.turn_on: cover_close_01_out02
    close_duration: 60s
    tilt_duration: 2s
    stop_action:
      - switch.turn_off: cover_open_01_out01
      - switch.turn_off: cover_close_01_out02

  - platform: venetian_blinds
    name: 'EZ SÜD'
    id: cover_02
    device_class: blind
    open_action:
      - switch.turn_on: cover_open_02_out03
    open_duration: 60s
    close_action:
      - switch.turn_on: cover_close_02_out04
    close_duration: 60s
    tilt_duration: 2s
    stop_action:
      - switch.turn_off: cover_open_02_out03
      - switch.turn_off: cover_close_02_out04

  - platform: venetian_blinds
    name: 'EZ HEBE SÜD'
    id: cover_03
    device_class: blind
    open_action:
      - switch.turn_on: cover_open_03_out05
    open_duration: 60s
    close_action:
      - switch.turn_on: cover_close_03_out06
    close_duration: 60s
    tilt_duration: 2s
    stop_action:
      - switch.turn_off: cover_open_03_out05
      - switch.turn_off: cover_close_03_out06

  - platform: venetian_blinds
    name: 'EZ HEBE NORD'
    id: cover_04
    device_class: blind
    open_action:
      - switch.turn_on: cover_open_04_out07
    open_duration: 60s
    close_action:
      - switch.turn_on: cover_close_04_out08
    close_duration: 60s
    tilt_duration: 2s
    stop_action:
      - switch.turn_off: cover_open_04_out07
      - switch.turn_off: cover_close_04_out08

  - platform: venetian_blinds
    name: 'WZ'
    id: cover_05
    device_class: blind
    open_action:
      - switch.turn_on: cover_open_05_out09
    open_duration: 60s
    close_action:
      - switch.turn_on: cover_close_05_out10
    close_duration: 60s
    tilt_duration: 2s
    stop_action:
      - switch.turn_off: cover_open_05_out09
      - switch.turn_off: cover_close_05_out10

  - platform: time_based
    name: 'Gäste West'
    id: cover_06
    device_class: shutter
    open_action:
      - switch.turn_on: cover_open_06_out11
    open_duration: 60s
    close_action:
      - switch.turn_on: cover_close_06_out12
    close_duration: 60s
    stop_action:
      - switch.turn_off: cover_open_06_out11
      - switch.turn_off: cover_close_06_out12

  - platform: time_based
    name: 'Gäste Nord'
    id: cover_07
    device_class: shutter
    open_action:
      - switch.turn_on: cover_open_07_out13
    open_duration: 60s
    close_action:
      - switch.turn_on: cover_close_07_out14
    close_duration: 60s
    stop_action:
      - switch.turn_off: cover_open_07_out13
      - switch.turn_off: cover_close_07_out14

  - platform: time_based
    name: 'KZ OST OST'
    id: cover_08
    device_class: shutter
    open_action:
      - switch.turn_on: cover_open_08_out15
    open_duration: 60s
    close_action:
      - switch.turn_on: cover_close_08_out16
    close_duration: 60s
    stop_action:
      - switch.turn_off: cover_open_08_out15
      - switch.turn_off: cover_close_08_out16

  - platform: time_based
    name: 'KZ OST SÜD'
    id: cover_09
    device_class: shutter
    open_action:
      - switch.turn_on: cover_open_09_out17
    open_duration: 60s
    close_action:
      - switch.turn_on: cover_close_09_out18
    close_duration: 60s
    stop_action:
      - switch.turn_off: cover_open_09_out17
      - switch.turn_off: cover_close_09_out18

  - platform: time_based
    name: 'KZ WEST SÜD'
    id: cover_10
    device_class: shutter
    open_action:
      - switch.turn_on: cover_open_10_out19
    open_duration: 60s
    close_action:
      - switch.turn_on: cover_close_10_out20
    close_duration: 60s
    stop_action:
      - switch.turn_off: cover_open_10_out19
      - switch.turn_off: cover_close_10_out20

  - platform: time_based
    name: 'KZ WEST WEST'
    id: cover_11
    device_class: shutter
    open_action:
      - switch.turn_on: cover_open_11_out21
    open_duration: 60s
    close_action:
      - switch.turn_on: cover_close_11_out22
    close_duration: 60s
    stop_action:
      - switch.turn_off: cover_open_11_out21
      - switch.turn_off: cover_close_11_out22

  - platform: time_based
    name: 'SR'
    id: cover_12
    device_class: shutter
    open_action:
      - switch.turn_on: cover_open_12_out23
    open_duration: 60s
    close_action:
      - switch.turn_on: cover_close_12_out24
    close_duration: 60s
    stop_action:
      - switch.turn_off: cover_open_12_out23
      - switch.turn_off: cover_close_12_out24

  - platform: time_based
    name: 'SZ'
    id: cover_13
    device_class: shutter
    open_action:
      - switch.turn_on: cover_open_13_out25
    open_duration: 60s
    close_action:
      - switch.turn_on: cover_close_13_out26
    close_duration: 60s
    stop_action:
      - switch.turn_off: cover_open_13_out25
      - switch.turn_off: cover_close_13_out26

  - platform: time_based
    name: 'ReserveRaff'
    id: cover_14
    device_class: shutter
    open_action:
      - switch.turn_on: cover_open_14_out27
    open_duration: 60s
    close_action:
      - switch.turn_on: cover_close_14_out28
    close_duration: 60s
    stop_action:
      - switch.turn_off: cover_open_14_out27
      - switch.turn_off: cover_close_14_out28

binary_sensor:
  - platform: gpio
    name: 'IN 01 - Küche'
    id: in_01
    pin:
      pcf8574: pcf_inputs_1to14
      number: 0
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on_off: 20ms

  - platform: gpio
    name: 'IN 02 - EZ SÜD'
    id: in_02
    pin:
      pcf8574: pcf_inputs_1to14
      number: 1
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on_off: 20ms

  - platform: gpio
    name: 'IN 03 - EZ HEBE SÜD'
    id: in_03
    pin:
      pcf8574: pcf_inputs_1to14
      number: 2
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on_off: 20ms

  - platform: gpio
    name: 'IN 04 - EZ HEBE NORD'
    id: in_04
    pin:
      pcf8574: pcf_inputs_1to14
      number: 3
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on_off: 20ms

  - platform: gpio
    name: 'IN 05 - WZ'
    id: in_05
    pin:
      pcf8574: pcf_inputs_1to14
      number: 4
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on_off: 20ms

  - platform: gpio
    name: 'IN 06 - Gäste West'
    id: in_06
    pin:
      pcf8574: pcf_inputs_1to14
      number: 5
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on_off: 20ms

  - platform: gpio
    name: 'IN 07 - Gäste Nord'
    id: in_07
    pin:
      pcf8574: pcf_inputs_1to14
      number: 6
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on_off: 20ms

  - platform: gpio
    name: 'IN 08 - KZ OST OST'
    id: in_08
    pin:
      pcf8574: pcf_inputs_1to14
      number: 8
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on_off: 20ms

  - platform: gpio
    name: 'IN 09 - KZ OST SÜD'
    id: in_09
    pin:
      pcf8574: pcf_inputs_1to14
      number: 9
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on_off: 20ms

  - platform: gpio
    name: 'IN 10 - KZ WEST SÜD'
    id: in_10
    pin:
      pcf8574: pcf_inputs_1to14
      number: 10
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on_off: 20ms

  - platform: gpio
    name: 'IN 11 - KZ WEST WEST'
    id: in_11
    pin:
      pcf8574: pcf_inputs_1to14
      number: 11
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on_off: 20ms

  - platform: gpio
    name: 'IN 12 - SR'
    id: in_12
    pin:
      pcf8574: pcf_inputs_1to14
      number: 12
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on_off: 20ms

  - platform: gpio
    name: 'IN 13 - SZ'
    id: in_13
    pin:
      pcf8574: pcf_inputs_1to14
      number: 13
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on_off: 20ms

  - platform: gpio
    name: 'IN 14 - ReserveRaff'
    id: in_14
    pin:
      pcf8574: pcf_inputs_1to14
      number: 14
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on_off: 20ms

cover_button:
  - id: button_01
    cover_id: cover_01
    input_id: in_01
    tilt_enabled: true
    tilt_step: 10%

  - id: button_02
    cover_id: cover_02
    input_id: in_02
    tilt_enabled: true
    tilt_step: 10%

  - id: button_03
    cover_id: cover_03
    input_id: in_03
    tilt_enabled: true
    tilt_step: 10%

  - id: button_04
    cover_id: cover_04
    input_id: in_04
    tilt_enabled: true
    tilt_step: 10%

  - id: button_05
    cover_id: cover_05
    input_id: in_05
    tilt_enabled: true
    tilt_step: 10%

  - id: button_06
    cover_id: cover_06
    input_id: in_06

  - id: button_07
    cover_id: cover_07
    input_id: in_07

  - id: button_08
    cover_id: cover_08
    input_id: in_08

  - id: button_09
    cover_id: cover_09
    input_id: in_09

  - id: button_10
    cover_id: cover_10
    input_id: in_10

  - id: button_11
    cover_id: cover_11
    input_id: in_11

  - id: button_12
    cover_id: cover_12
    input_id: in_12

  - id: button_13
    cover_id: cover_13
    input_id: in_13

  - id: button_14
    cover_id: cover_14
    input_id: in_14

